INSERT INTO heroes VALUES (1, "Anti-Mage", "agi", "Melee", "Carry,Escape,Nuker", "/apps/dota2/images/heroes/antimage_full.png?", 2);
INSERT INTO heroes VALUES (2, "Axe", "str", "Melee", "Initiator,Durable,Disabler,Jungler", "/apps/dota2/images/heroes/axe_full.png?", 2);
INSERT INTO heroes VALUES (3, "Bane", "int", "Ranged", "Support,Disabler,Nuker,Durable", "/apps/dota2/images/heroes/bane_full.png?", 4);
INSERT INTO heroes VALUES (4, "Bloodseeker", "agi", "Melee", "Carry,Disabler,Jungler,Nuker,Initiator", "/apps/dota2/images/heroes/bloodseeker_full.png?", 2);
INSERT INTO heroes VALUES (5, "Crystal Maiden", "int", "Ranged", "Support,Disabler,Nuker,Jungler", "/apps/dota2/images/heroes/crystal_maiden_full.png?", 2);
INSERT INTO heroes VALUES (6, "Drow Ranger", "agi", "Ranged", "Carry,Disabler,Pusher", "/apps/dota2/images/heroes/drow_ranger_full.png?", 2);
INSERT INTO heroes VALUES (7, "Earthshaker", "str", "Melee", "Support,Initiator,Disabler,Nuker", "/apps/dota2/images/heroes/earthshaker_full.png?", 2);
INSERT INTO heroes VALUES (8, "Juggernaut", "agi", "Melee", "Carry,Pusher,Escape", "/apps/dota2/images/heroes/juggernaut_full.png?", 2);
INSERT INTO heroes VALUES (9, "Mirana", "agi", "Ranged", "Carry,Support,Escape,Nuker,Disabler", "/apps/dota2/images/heroes/mirana_full.png?", 2);
INSERT INTO heroes VALUES (10, "Morphling", "agi", "Ranged", "Carry,Escape,Durable,Nuker,Disabler", "/apps/dota2/images/heroes/morphling_full.png?", 0);
INSERT INTO heroes VALUES (11, "Shadow Fiend", "agi", "Ranged", "Carry,Nuker", "/apps/dota2/images/heroes/nevermore_full.png?", 0);
INSERT INTO heroes VALUES (12, "Phantom Lancer", "agi", "Melee", "Carry,Escape,Pusher,Nuker", "/apps/dota2/images/heroes/phantom_lancer_full.png?", 2);
INSERT INTO heroes VALUES (13, "Puck", "int", "Ranged", "Initiator,Disabler,Escape,Nuker", "/apps/dota2/images/heroes/puck_full.png?", 2);
INSERT INTO heroes VALUES (14, "Pudge", "str", "Melee", "Disabler,Initiator,Durable,Nuker", "/apps/dota2/images/heroes/pudge_full.png?", 2);
INSERT INTO heroes VALUES (15, "Razor", "agi", "Ranged", "Carry,Durable,Nuker,Pusher", "/apps/dota2/images/heroes/razor_full.png?", 0);
INSERT INTO heroes VALUES (16, "Sand King", "str", "Melee", "Initiator,Disabler,Support,Nuker,Escape,Jungler", "/apps/dota2/images/heroes/sand_king_full.png?", 6);
INSERT INTO heroes VALUES (17, "Storm Spirit", "int", "Ranged", "Carry,Escape,Nuker,Initiator,Disabler", "/apps/dota2/images/heroes/storm_spirit_full.png?", 2);
INSERT INTO heroes VALUES (18, "Sven", "str", "Melee", "Carry,Disabler,Initiator,Durable,Nuker", "/apps/dota2/images/heroes/sven_full.png?", 2);
INSERT INTO heroes VALUES (19, "Tiny", "str", "Melee", "Carry,Nuker,Pusher,Initiator,Durable,Disabler", "/apps/dota2/images/heroes/tiny_full.png?", 2);
INSERT INTO heroes VALUES (20, "Vengeful Spirit", "agi", "Ranged", "Support,Initiator,Disabler,Nuker,Escape", "/apps/dota2/images/heroes/vengefulspirit_full.png?", 2);
INSERT INTO heroes VALUES (21, "Windranger", "int", "Ranged", "Carry,Support,Disabler,Escape,Nuker", "/apps/dota2/images/heroes/windrunner_full.png?", 2);
INSERT INTO heroes VALUES (22, "Zeus", "int", "Ranged", "Nuker", "/apps/dota2/images/heroes/zuus_full.png?", 2);
INSERT INTO heroes VALUES (23, "Kunkka", "str", "Melee", "Carry,Support,Disabler,Initiator,Durable,Nuker", "/apps/dota2/images/heroes/kunkka_full.png?", 2);
INSERT INTO heroes VALUES (25, "Lina", "int", "Ranged", "Support,Carry,Nuker,Disabler", "/apps/dota2/images/heroes/lina_full.png?", 2);
INSERT INTO heroes VALUES (26, "Lion", "int", "Ranged", "Support,Disabler,Nuker,Initiator", "/apps/dota2/images/heroes/lion_full.png?", 2);
INSERT INTO heroes VALUES (27, "Shadow Shaman", "int", "Ranged", "Support,Pusher,Disabler,Nuker,Initiator", "/apps/dota2/images/heroes/shadow_shaman_full.png?", 2);
INSERT INTO heroes VALUES (28, "Slardar", "str", "Melee", "Carry,Durable,Initiator,Disabler,Escape", "/apps/dota2/images/heroes/slardar_full.png?", 0);
INSERT INTO heroes VALUES (29, "Tidehunter", "str", "Melee", "Initiator,Durable,Disabler,Nuker", "/apps/dota2/images/heroes/tidehunter_full.png?", 2);
INSERT INTO heroes VALUES (30, "Witch Doctor", "int", "Ranged", "Support,Nuker,Disabler", "/apps/dota2/images/heroes/witch_doctor_full.png?", 2);
INSERT INTO heroes VALUES (31, "Lich", "int", "Ranged", "Support,Nuker", "/apps/dota2/images/heroes/lich_full.png?", 2);
INSERT INTO heroes VALUES (32, "Riki", "agi", "Melee", "Carry,Escape,Disabler", "/apps/dota2/images/heroes/riki_full.png?", 2);
INSERT INTO heroes VALUES (33, "Enigma", "int", "Ranged", "Disabler,Jungler,Initiator,Pusher", "/apps/dota2/images/heroes/enigma_full.png?", 0);
INSERT INTO heroes VALUES (34, "Tinker", "int", "Ranged", "Carry,Nuker,Pusher", "/apps/dota2/images/heroes/tinker_full.png?", 2);
INSERT INTO heroes VALUES (35, "Sniper", "agi", "Ranged", "Carry,Nuker", "/apps/dota2/images/heroes/sniper_full.png?", 2);
INSERT INTO heroes VALUES (36, "Necrophos", "int", "Ranged", "Carry,Nuker,Durable,Disabler", "/apps/dota2/images/heroes/necrolyte_full.png?", 2);
INSERT INTO heroes VALUES (37, "Warlock", "int", "Ranged", "Support,Initiator,Disabler", "/apps/dota2/images/heroes/warlock_full.png?", 2);
INSERT INTO heroes VALUES (38, "Beastmaster", "str", "Melee", "Initiator,Disabler,Durable,Nuker", "/apps/dota2/images/heroes/beastmaster_full.png?", 2);
INSERT INTO heroes VALUES (39, "Queen of Pain", "int", "Ranged", "Carry,Nuker,Escape", "/apps/dota2/images/heroes/queenofpain_full.png?", 2);
INSERT INTO heroes VALUES (40, "Venomancer", "agi", "Ranged", "Support,Nuker,Initiator,Pusher,Disabler", "/apps/dota2/images/heroes/venomancer_full.png?", 0);
INSERT INTO heroes VALUES (41, "Faceless Void", "agi", "Melee", "Carry,Initiator,Disabler,Escape,Durable", "/apps/dota2/images/heroes/faceless_void_full.png?", 2);
INSERT INTO heroes VALUES (42, "Wraith King", "str", "Melee", "Carry,Support,Durable,Disabler,Initiator", "/apps/dota2/images/heroes/skeleton_king_full.png?", 2);
INSERT INTO heroes VALUES (43, "Death Prophet", "int", "Ranged", "Carry,Pusher,Nuker,Disabler", "/apps/dota2/images/heroes/death_prophet_full.png?", 2);
INSERT INTO heroes VALUES (44, "Phantom Assassin", "agi", "Melee", "Carry,Escape", "/apps/dota2/images/heroes/phantom_assassin_full.png?", 2);
INSERT INTO heroes VALUES (45, "Pugna", "int", "Ranged", "Nuker,Pusher", "/apps/dota2/images/heroes/pugna_full.png?", 2);
INSERT INTO heroes VALUES (46, "Templar Assassin", "agi", "Ranged", "Carry,Escape", "/apps/dota2/images/heroes/templar_assassin_full.png?", 2);
INSERT INTO heroes VALUES (47, "Viper", "agi", "Ranged", "Carry,Durable,Initiator,Disabler", "/apps/dota2/images/heroes/viper_full.png?", 0);
INSERT INTO heroes VALUES (48, "Luna", "agi", "Ranged", "Carry,Nuker,Pusher", "/apps/dota2/images/heroes/luna_full.png?", 2);
INSERT INTO heroes VALUES (49, "Dragon Knight", "str", "Melee", "Carry,Pusher,Durable,Disabler,Initiator,Nuker", "/apps/dota2/images/heroes/dragon_knight_full.png?", 2);
INSERT INTO heroes VALUES (50, "Dazzle", "int", "Ranged", "Support,Nuker,Disabler", "/apps/dota2/images/heroes/dazzle_full.png?", 2);
INSERT INTO heroes VALUES (51, "Clockwerk", "str", "Melee", "Initiator,Disabler,Durable,Nuker", "/apps/dota2/images/heroes/rattletrap_full.png?", 2);
INSERT INTO heroes VALUES (52, "Leshrac", "int", "Ranged", "Carry,Support,Nuker,Pusher,Disabler", "/apps/dota2/images/heroes/leshrac_full.png?", 4);
INSERT INTO heroes VALUES (53, "Nature's Prophet", "int", "Ranged", "Carry,Jungler,Pusher,Escape,Nuker", "/apps/dota2/images/heroes/furion_full.png?", 2);
INSERT INTO heroes VALUES (54, "Lifestealer", "str", "Melee", "Carry,Durable,Jungler,Escape,Disabler", "/apps/dota2/images/heroes/life_stealer_full.png?", 2);
INSERT INTO heroes VALUES (55, "Dark Seer", "int", "Melee", "Initiator,Jungler,Escape,Disabler", "/apps/dota2/images/heroes/dark_seer_full.png?", 2);
INSERT INTO heroes VALUES (56, "Clinkz", "agi", "Ranged", "Carry,Escape,Pusher", "/apps/dota2/images/heroes/clinkz_full.png?", 2);
INSERT INTO heroes VALUES (57, "Omniknight", "str", "Melee", "Support,Durable,Nuker", "/apps/dota2/images/heroes/omniknight_full.png?", 2);
INSERT INTO heroes VALUES (58, "Enchantress", "int", "Ranged", "Support,Jungler,Pusher,Durable,Disabler", "/apps/dota2/images/heroes/enchantress_full.png?", 4);
INSERT INTO heroes VALUES (59, "Huskar", "str", "Ranged", "Carry,Durable,Initiator", "/apps/dota2/images/heroes/huskar_full.png?", 2);
INSERT INTO heroes VALUES (60, "Night Stalker", "str", "Melee", "Carry,Initiator,Durable,Disabler,Nuker", "/apps/dota2/images/heroes/night_stalker_full.png?", 2);
INSERT INTO heroes VALUES (61, "Broodmother", "agi", "Melee", "Carry,Pusher,Escape,Nuker", "/apps/dota2/images/heroes/broodmother_full.png?", 8);
INSERT INTO heroes VALUES (62, "Bounty Hunter", "agi", "Melee", "Escape,Nuker", "/apps/dota2/images/heroes/bounty_hunter_full.png?", 2);
INSERT INTO heroes VALUES (63, "Weaver", "agi", "Ranged", "Carry,Escape", "/apps/dota2/images/heroes/weaver_full.png?", 4);
INSERT INTO heroes VALUES (64, "Jakiro", "int", "Ranged", "Support,Nuker,Pusher,Disabler", "/apps/dota2/images/heroes/jakiro_full.png?", 2);
INSERT INTO heroes VALUES (65, "Batrider", "int", "Ranged", "Initiator,Jungler,Disabler,Escape", "/apps/dota2/images/heroes/batrider_full.png?", 2);
INSERT INTO heroes VALUES (66, "Chen", "int", "Ranged", "Support,Jungler,Pusher", "/apps/dota2/images/heroes/chen_full.png?", 2);
INSERT INTO heroes VALUES (67, "Spectre", "agi", "Melee", "Carry,Durable,Escape", "/apps/dota2/images/heroes/spectre_full.png?", 0);
INSERT INTO heroes VALUES (68, "Ancient Apparition", "int", "Ranged", "Support,Disabler,Nuker", "/apps/dota2/images/heroes/ancient_apparition_full.png?", 2);
INSERT INTO heroes VALUES (69, "Doom", "str", "Melee", "Carry,Disabler,Initiator,Durable,Nuker", "/apps/dota2/images/heroes/doom_bringer_full.png?", 2);
INSERT INTO heroes VALUES (70, "Ursa", "agi", "Melee", "Carry,Jungler,Durable,Disabler", "/apps/dota2/images/heroes/ursa_full.png?", 2);
INSERT INTO heroes VALUES (71, "Spirit Breaker", "str", "Melee", "Carry,Initiator,Disabler,Durable,Escape", "/apps/dota2/images/heroes/spirit_breaker_full.png?", 2);
INSERT INTO heroes VALUES (72, "Gyrocopter", "agi", "Ranged", "Carry,Nuker,Disabler", "/apps/dota2/images/heroes/gyrocopter_full.png?", 2);
INSERT INTO heroes VALUES (73, "Alchemist", "str", "Melee", "Carry,Support,Durable,Disabler,Initiator,Nuker", "/apps/dota2/images/heroes/alchemist_full.png?", 2);
INSERT INTO heroes VALUES (74, "Invoker", "int", "Ranged", "Carry,Nuker,Disabler,Escape,Pusher", "/apps/dota2/images/heroes/invoker_full.png?", 2);
INSERT INTO heroes VALUES (75, "Silencer", "int", "Ranged", "Carry,Support,Disabler,Initiator,Nuker", "/apps/dota2/images/heroes/silencer_full.png?", 2);
INSERT INTO heroes VALUES (76, "Outworld Devourer", "int", "Ranged", "Carry,Nuker,Disabler", "/apps/dota2/images/heroes/obsidian_destroyer_full.png?", 4);
INSERT INTO heroes VALUES (77, "Lycan", "str", "Melee", "Carry,Pusher,Jungler,Durable,Escape", "/apps/dota2/images/heroes/lycan_full.png?", 2);
INSERT INTO heroes VALUES (78, "Brewmaster", "str", "Melee", "Carry,Initiator,Durable,Disabler,Nuker", "/apps/dota2/images/heroes/brewmaster_full.png?", 2);
INSERT INTO heroes VALUES (79, "Shadow Demon", "int", "Ranged", "Support,Disabler,Initiator,Nuker", "/apps/dota2/images/heroes/shadow_demon_full.png?", 2);
INSERT INTO heroes VALUES (80, "Lone Druid", "agi", "Ranged", "Carry,Pusher,Jungler,Durable", "/apps/dota2/images/heroes/lone_druid_full.png?", 2);
INSERT INTO heroes VALUES (81, "Chaos Knight", "str", "Melee", "Carry,Disabler,Durable,Pusher,Initiator", "/apps/dota2/images/heroes/chaos_knight_full.png?", 2);
INSERT INTO heroes VALUES (82, "Meepo", "agi", "Melee", "Carry,Escape,Nuker,Disabler,Initiator,Pusher", "/apps/dota2/images/heroes/meepo_full.png?", 2);
INSERT INTO heroes VALUES (83, "Treant Protector", "str", "Melee", "Support,Initiator,Durable,Disabler,Escape", "/apps/dota2/images/heroes/treant_full.png?", 2);
INSERT INTO heroes VALUES (84, "Ogre Magi", "int", "Melee", "Support,Nuker,Disabler,Durable,Initiator", "/apps/dota2/images/heroes/ogre_magi_full.png?", 2);
INSERT INTO heroes VALUES (85, "Undying", "str", "Melee", "Support,Durable,Disabler,Nuker", "/apps/dota2/images/heroes/undying_full.png?", 2);
INSERT INTO heroes VALUES (86, "Rubick", "int", "Ranged", "Support,Disabler,Nuker", "/apps/dota2/images/heroes/rubick_full.png?", 2);
INSERT INTO heroes VALUES (87, "Disruptor", "int", "Ranged", "Support,Disabler,Nuker,Initiator", "/apps/dota2/images/heroes/disruptor_full.png?", 2);
INSERT INTO heroes VALUES (88, "Nyx Assassin", "agi", "Melee", "Disabler,Nuker,Initiator,Escape", "/apps/dota2/images/heroes/nyx_assassin_full.png?", 6);
INSERT INTO heroes VALUES (89, "Naga Siren", "agi", "Melee", "Carry,Support,Pusher,Disabler,Initiator,Escape", "/apps/dota2/images/heroes/naga_siren_full.png?", 0);
INSERT INTO heroes VALUES (90, "Keeper of the Light", "int", "Ranged", "Support,Nuker,Disabler,Jungler", "/apps/dota2/images/heroes/keeper_of_the_light_full.png?", 2);
INSERT INTO heroes VALUES (91, "Io", "str", "Ranged", "Support,Escape,Nuker", "/apps/dota2/images/heroes/wisp_full.png?", 0);
INSERT INTO heroes VALUES (92, "Visage", "int", "Ranged", "Support,Nuker,Durable,Disabler,Pusher", "/apps/dota2/images/heroes/visage_full.png?", 2);
INSERT INTO heroes VALUES (93, "Slark", "agi", "Melee", "Carry,Escape,Disabler,Nuker", "/apps/dota2/images/heroes/slark_full.png?", 2);
INSERT INTO heroes VALUES (94, "Medusa", "agi", "Ranged", "Carry,Disabler,Durable", "/apps/dota2/images/heroes/medusa_full.png?", 0);
INSERT INTO heroes VALUES (95, "Troll Warlord", "agi", "Ranged", "Carry,Pusher,Disabler,Durable", "/apps/dota2/images/heroes/troll_warlord_full.png?", 2);
INSERT INTO heroes VALUES (96, "Centaur Warrunner", "str", "Melee", "Durable,Initiator,Disabler,Nuker,Escape", "/apps/dota2/images/heroes/centaur_full.png?", 4);
INSERT INTO heroes VALUES (97, "Magnus", "str", "Melee", "Initiator,Disabler,Nuker,Escape", "/apps/dota2/images/heroes/magnataur_full.png?", 4);
INSERT INTO heroes VALUES (98, "Timbersaw", "str", "Melee", "Nuker,Durable,Escape", "/apps/dota2/images/heroes/shredder_full.png?", 2);
INSERT INTO heroes VALUES (99, "Bristleback", "str", "Melee", "Carry,Durable,Initiator,Nuker", "/apps/dota2/images/heroes/bristleback_full.png?", 2);
INSERT INTO heroes VALUES (100, "Tusk", "str", "Melee", "Initiator,Disabler,Nuker", "/apps/dota2/images/heroes/tusk_full.png?", 2);
INSERT INTO heroes VALUES (101, "Skywrath Mage", "int", "Ranged", "Support,Nuker,Disabler", "/apps/dota2/images/heroes/skywrath_mage_full.png?", 2);
INSERT INTO heroes VALUES (102, "Abaddon", "str", "Melee", "Support,Carry,Durable", "/apps/dota2/images/heroes/abaddon_full.png?", 2);
INSERT INTO heroes VALUES (103, "Elder Titan", "str", "Melee", "Initiator,Disabler,Nuker,Durable", "/apps/dota2/images/heroes/elder_titan_full.png?", 2);
INSERT INTO heroes VALUES (104, "Legion Commander", "str", "Melee", "Carry,Disabler,Initiator,Durable,Nuker", "/apps/dota2/images/heroes/legion_commander_full.png?", 2);
INSERT INTO heroes VALUES (105, "Techies", "int", "Ranged", "Nuker,Disabler", "/apps/dota2/images/heroes/techies_full.png?", 6);
INSERT INTO heroes VALUES (106, "Ember Spirit", "agi", "Melee", "Carry,Escape,Nuker,Disabler,Initiator", "/apps/dota2/images/heroes/ember_spirit_full.png?", 2);
INSERT INTO heroes VALUES (107, "Earth Spirit", "str", "Melee", "Nuker,Escape,Disabler,Initiator,Durable", "/apps/dota2/images/heroes/earth_spirit_full.png?", 2);
INSERT INTO heroes VALUES (108, "Underlord", "str", "Melee", "Support,Nuker,Disabler,Durable,Escape", "/apps/dota2/images/heroes/abyssal_underlord_full.png?", 2);
INSERT INTO heroes VALUES (109, "Terrorblade", "agi", "Melee", "Carry,Pusher,Nuker", "/apps/dota2/images/heroes/terrorblade_full.png?", 2);
INSERT INTO heroes VALUES (110, "Phoenix", "str", "Ranged", "Support,Nuker,Initiator,Escape,Disabler", "/apps/dota2/images/heroes/phoenix_full.png?", 2);
INSERT INTO heroes VALUES (111, "Oracle", "int", "Ranged", "Support,Nuker,Disabler,Escape", "/apps/dota2/images/heroes/oracle_full.png?", 2);
INSERT INTO heroes VALUES (112, "Winter Wyvern", "int", "Ranged", "Support,Disabler,Nuker", "/apps/dota2/images/heroes/winter_wyvern_full.png?", 2);
INSERT INTO heroes VALUES (113, "Arc Warden", "agi", "Ranged", "Carry,Escape,Nuker", "/apps/dota2/images/heroes/arc_warden_full.png?", 2);
INSERT INTO heroes VALUES (114, "Monkey King", "agi", "Melee", "Carry,Escape,Disabler,Initiator", "/apps/dota2/images/heroes/monkey_king_full.png?", 2);
INSERT INTO heroes VALUES (119, "Dark Willow", "int", "Ranged", "Support,Nuker,Disabler,Escape", "/apps/dota2/images/heroes/dark_willow_full.png?", 2);
INSERT INTO heroes VALUES (120, "Pangolier", "agi", "Melee", "Carry,Nuker,Disabler,Durable,Escape,Initiator", "/apps/dota2/images/heroes/pangolier_full.png?", 2);