/*
The users' info is stored in the table users with the following structure:

first_name: user's first name;
second_name: user's last name;
attribute: a unique attribute string of this user.
It seems that only the users those attribute was generated by the old version of your special algorithm were affected. Such attributes have the following format (accurate to letter cases): %_%. It's your duty now to warn the users that have these attributes about possible risks.

Given the users table, compose the resulting table consisting only of the rows that contain affected users' info. The result should be sorted by the attributes in ascending order.
*/

/*Please add ; after each select statement*/
CREATE PROCEDURE securityBreach()
BEGIN
	SELECT *
    FROM users
    WHERE attribute REGEXP BINARY CONCAT('[a-zA-Z0-9]%', CONCAT(first_name, '_',second_name), '%')
    ORDER BY attribute ASC;
END